// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkbbmkdysrofurjcpbib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRrYmJta2R5c3JvZnVyamNwYmliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NjIxNzQsImV4cCI6MjA3MDMzODE3NH0.j7FNG5JgMTv_sH-8ZrAFGl73DL6XhOsob84IIm4c-kQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});